services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./server/.env.test

  api:
    container_name: api
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - ./server/.env.test