services:
  postgres:
    build:
      context: ./server
      dockerfile: Dockerfile.pg
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - ./server/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./server
    ports:
      - 5000:5000
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - server/.env

  next-app:
    container_name: next-app
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/src:/app/src
      - ./web/public:/app/public

  openssl:
    build: ./openssl
    volumes:
      - ssl-certs:/certs

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ssl-certs:/certs
    depends_on:
      - postgres
      - api
      - next-app
      - openssl
      
volumes:
  postgres-volume:
  ssl-certs:
