services:
  api:
    container_name: api_test
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - ./server/.env.test

  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres
    ports:
      - 5433:5432
    env_file:
      - server/.env.test

